### ISSUE TITLE
请问data_manager.py文件第536行和第539行，

### ISSUE THREAD

**Issue by ghost** [guxinqian/TKP#3]
第536行：for pdir in pdirs: 这里的pdir是一个  /data/datasets/DukeMTMC-VideoReID/train/0002_c1_f0044158.jpg 这样的形式，然后第539行：tdirs = glob.glob(osp.join(pdir, '*'))；这里得到的tdirs是一个空列表。请问这里的tdirs是什么含义，这里得到空列表后程序不能向下运行了。

**Comment by guxinqian** [comment]
可能你解压的数据集有问题。train的子目录应该是ID文件夹，再下一级是该ID所有tracklet。tdirs应该是tracklet的路径。你的pdir就是有问题的，你用的应该是duke的image-based dataset，你需要重新下载video-based dataset。

**Comment by ghost** [comment]
谢谢您，正如您所说的问题。我下载的是duke的image-based dataset。多谢您的回复。
