### ISSUE TITLE
关于复现精度的问题

### ISSUE THREAD

**Issue by bigmoking** [guxinqian/TKP#4]
大佬您好：
        最近在跑您的TKP代码，环境和,您一样都是pytorch1.0.0 python3.6，代码直从您的githup  copy,但是三个数据集没有一个达到您的精度，比如iLIDS-VID这个数据集，我的结果rank1 40.0，远远低于您的结果，还望解答。谢谢！

**Comment by guxinqian** [comment]
Market和Duke跑完需要用全帧测试一下，train.py里的测试只用了4帧，test.py是全帧，这个性能会有差异。另外正常实验误差可能在2%以内，多跑几次会不一样。iLIDS的结果是极不稳定的，每个epoch的性能甚至都能差10个点，你想得到比较高的结果可以每个epoch测一次。然后iLIDS0-9十次划分的点数差异也非常大，最大可能能差20%，论文里是求的10次平均。另外用Duke的pretrain预训练参数会比Market高，然后paper里报告的是用欧氏距离测得，后面改成余弦距离发现可以再涨10个点，但是论文里没有改。

**Comment by bigmoking** [comment]
好的   十分感谢！

guxinqian <notifications@github.com> 于2020年7月9日周四 上午11:08写道：

**Comment by guxinqian** [comment]
我有检查了一下代码，iLIDS的测试github这一版已经是cosine similarity了，你只需要load你Duke pretrained的model，然后改一下eval_step应该就能跑出来比论文里更高的结果。如果你试过还有问题可以继续联系我。

**Comment by bigmoking** [comment]
您的这句话“ 另外用Duke的pretrain预训练参数 会比Market高  ” 意思是指Duke数据集给的预训练模型吗？目前是一名新手，多有打扰。

hongyu qian <hongyuqian934@gmail.com> 于2020年7月9日周四 下午2:32写道：

**Comment by bigmoking** [comment]
好的 好的  十分感谢。

guxinqian <notifications@github.com> 于2020年7月9日周四 下午2:43写道：

**Comment by guxinqian** [comment]
是的。iLIDS太小了，波动很大。不是很建议在iLIDS上继续实验，写论文的话两个数据集也能说明问题了。如果还想继续实验可以用ICCV19那个新数据集LS-VID

**Comment by bigmoking** [comment]
好的  实在是太感谢了
guxinqian <notifications@github.com> 于2020年7月9日周四 下午2:48写道：
