### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by 1691077362** [guxinqian/TKP#8]
Can you share the data sets you use ?The link you gave is no longer good.

**Comment by guxinqian** [comment]
The use of some datasets need agree with the protocol. In addition, DukeMTMC has not be allowed to be used in academic papers. You can send an e-mail to the authors of corresponding dataset for download link.

**Comment by 1691077362** [comment]
thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guxinqian/TKP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 上午10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guxinqian/TKP] data set (Issue #8)





 
The use of some datasets need agree with the protocol. In addition, DukeMTMC has not be allowed to be used in academic papers. You can send an e-mail to the authors of corresponding dataset for download link.

**Comment by 1691077362** [comment]
Does the iLIDS-VID dataset also need to send an email to the author to get a download link ?

**Comment by guxinqian** [comment]
iLIDS-VID does not involve the protocol of usage. You can send an email to me(xinqiangu@gmail.com). Then, I send my iLIDS-VID datset to you.
